### ISSUE TITLE
Do not ask user to process variables into `RCLONE_CONFIG` var

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/cxe2stix_helper#2]
Currently you need to base64 encode

cf account id
cf key
cf secret

doing this introduces the likelihood of error by the user.

instead ask user for 

```
CLOUDFLARE_ACCOUNT_ID
CLOUDFLARE_ACCESS_KEY_ID
CLOUDFLARE_ACCESS_KEY_SECRET
```

and process the rclone config key dynamically

**Comment by fqrious** [comment]
no, this is how all rclone actions in marketplace work... we just need to document it



![Image](https://github.com/user-attachments/assets/83cdc704-78c7-4f48-ab6f-817fc71e5b88)

**Comment by fqrious** [comment]
This also has the advantage that user can use their own provider instead of cloudflare

**Comment by fqrious** [comment]
I added support for `CLOUDFLARE_*` but it's only used if `RCLONE_CONFIG` isn't set
